name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ec348df0f48f67baba0366139559405546e1bb36672b13d2d1c411315f401f1"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
