name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25715a897a202159ce3572d87a88838128003fe4bdf6e35434def208dbfb5e66"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
