name = "fdua"
author = "Fery - Based on DRSS (By Devin)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c27ac83f543834e0cbc7dac349ba8e3e6bf6c629530106872cbeee94f2f788d9"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
