name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8667adfabcdf746fd020eae7d342cadb58017f6074e8aab5cded77d5c0db3185"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
