name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64d48d32889cb299648e81a5359a1bf79857d3d7380add086c844473c42df0ed"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
