name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e00f4917ccde604e277deee506672008420553566e46fb9d8c54eba3077f4e83"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
