name = "fdua"
author = "Fery - Based on DRSS (By Devin)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97e2e1ed690c78cefd5540785875197851ca064e741ecf32bcfe324243eaf433"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
