name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "011a284952ceb801b48bcfcfcd5ac0c4e4a235346d70f4409d2bba9a15a6e177"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
