name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcf7e03a3cf422ce74ad1e9420b24d284c2e2a2c0e138f34b7415173fc006fce"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
