name = "fdua"
author = "Fery - Based on DRSS (By Devin)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acb58d4d78f2ccadd69d4fcd3535b726b52414489e88418cbddcc566327a9365"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
