name = "drss"
author = "intergrav"
version = "1.0.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8cfd27ad0a14b6a5d5171908d7e76973d61b3d3d59aba160425e568a08e0dd5"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
